on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install jq
    - name: Check if issue is created by collaborator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        is_collaborator=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.event.issue.user.login }}" | jq -r '.message')

        if [ "$is_collaborator" == "Not Found" ]; then
          echo "Issue not created by a collaborator. Skipping action."
          exit 78
        fi
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 1
    - name: AutoPR
      uses: ./
      with:
        event: ${{ toJson(github.event) }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        codegen_agent_id: rail-v1
        pull_request_agent_id: rail-v1
        base_branch: main
        model: gpt-4
        context_limit: 8192
        min_tokens: 1000
        max_tokens: 2000
        num_reasks: 2
