on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  autopr:
    if: ${{ (github.event_name == 'issues' && 
             contains( github.event.label.name, 'AutoPR')) || 
            (github.event_name == 'issue_comment' && 
             github.event.issue.pull_request &&
             contains( github.event.comment.body, '@AutoPR')) }}
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install jq
    - name: Check if label was added by a collaborator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        is_collaborator=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.event.sender.login }}" | jq -r '.message')

        if [ "$is_collaborator" == "Not Found" ]; then
          echo "Label not added by a collaborator. Skipping action."
          exit 78
        fi
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 1
    - name: AutoPR
      uses: docker://ghcr.io/irgolic/autopr:latest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        codegen_agent_id: auto-v1
        pull_request_agent_id: rail-v1
        base_branch: main
        model: gpt-4
        context_limit: 8192
        min_tokens: 1000
        max_tokens: 2000
        num_reasks: 2
